### ISSUE TITLE
automatic deletion when backup volume is getting full

### ISSUE THREAD

**Issue by aloistr** [cytopia/linux-timemachine#10]
There appears to be no feature to automatically delete backups when the backup volume gets full.
Is this planned, at some point?

**Comment by cytopia** [comment]
I would say one tool for one task to keep things simple as possible.
For automated deletion I would recommend `tmpreaper` or `tmpwatch` (depends on the distro)

**Comment by cytopia** [comment]
Duplicate of https://github.com/cytopia/linux-timemachine/issues/26
