### ISSUE TITLE
Warning, when destination directory is empty

### ISSUE THREAD

**Issue by ehlers** [cytopia/linux-timemachine#12]
timemachine 29c73ecc05714f3bd7fb3ee9afc17548aa0b802c, rsync v3.1.2

When the destination directory is empty, running timemachine gives the warning "--link-dest arg does not exist: ../current". The backup is fine and following runs don't show this warning.

```
$ mkdir dest
$ ./timemachine etc dest
--link-dest arg does not exist: ../current
$ ./timemachine etc dest
$ 
```

**Comment by cytopia** [comment]
@ehlers I have fixed it and also added TravisCI integration tests for both Linux and OSX.
