### ISSUE TITLE
Travis brew issue

### ISSUE THREAD

**Issue by vedantpuri** [cytopia/linux-timemachine#18]
Hi,

I was hoping to contribute to your repo and made some changes. However, while running travis even though my linux tests pass, the macOS keeps on running in a loop.

The error was:
Error: invalid option: --with-default-names (while installing make)

I experience this issue on my mac as well, which indicates that the "--with-default-names" option is invalid. I hope you can look into this and fix it soon if possible!

Also, the travis build for my PR (now closed) is continuously running since it is retrying to install make and failing everytime due to the error above, so please stop that build. It would be great if, in the new fixed travis file there be a timeout mechanism.

Thanks

**Comment by vedantpuri** [comment]
Upon some investigation, I cam across [this StackOverFlow post](https://stackoverflow.com/questions/30003570/how-to-use-gnu-sed-on-mac-os-x) in which the reply says that HomeBrew doesn't support the "--with-default-names" options as of January 2019.

I hope you can fix the travis file soon, so that I can submit a new PR and contribute soon. :)

**Comment by cytopia** [comment]
Will be replaced with GitHub Actions: https://github.com/cytopia/linux-timemachine/pull/32
