### ISSUE TITLE
Make use of ionice/nice to allow less invasive backups

### ISSUE THREAD

**Issue by mzpqnxow** [cytopia/linux-timemachine#20]
@cytopia It would be nice to have a default and/or an option to ionice/nice the backup operation to reduce lag on the system during a backup. It is a pretty simple thing to add, I can PR it if you want, maybe you prefer to put it in?

**Comment by mzpqnxow** [comment]
No pun intended re: 'it would be *nice*' :)

**Comment by mzpqnxow** [comment]
One way to implement this without invoking nice/ionice in the linux-timemachine itself is using the method described [here](https://serverfault.com/questions/381488/rsync-ionice-destination)

I'm not sure what a good default would be, if there even is such a thing...

**Comment by cytopia** [comment]
Not sure if this will be compatible with BSD/MacOS. I am also trying to keep the script as small as possible to avoid potential bugs, as backing up should be trustworthy.

**Comment by cytopia** [comment]
@mzpqnxow I will close this as the behaviour on BSD and MacOS is not clear and it would make the code too complex. If you think this is a really needed feature, please let me know and I will re-open this issue and see if more people wish to see this happening.

**Comment by mzpqnxow** [comment]
@cytopia I agree with you, I hadn't considered compatibility
