### ISSUE TITLE
Explicit instructions on how to restore from backups

### ISSUE THREAD

**Issue by mzpqnxow** [cytopia/linux-timemachine#25]
Reading the documentation, it is not immediately clear how one would go about restoring from a backup. It would be nice to have this in the documentation.

**Comment by cytopia** [comment]
@mzpqnxow let me know if this is sufficient: https://github.com/cytopia/linux-timemachine#recycle-restore

**Comment by mzpqnxow** [comment]
@cytopia This is great, thank you for taking the time to add it. I'll close it out
