### ISSUE TITLE
Pruning of old backups

### ISSUE THREAD

**Issue by mzpqnxow** [cytopia/linux-timemachine#26]
There is a similar project [here](https://github.com/laurent22/rsync-time-backup) which uses a very convenient pruning logic to ensure short-term backups, long-term backups, and pruning of "old" backups using this logic:

> Backup sets are automatically deleted following a simple expiration strategy > > defined with the `--strategy` flag. This strategy is a series of time intervals > with each item being defined as `x:y`, which means "after x days, keep one backup > every y days". The default strategy is `1:1 30:7 365:30`, which means:
>
> - After **1** day, keep one backup every **1** day (**1:1**).
> - After **30** days, keep one backup every **7** days (**30:7**).
> - After **365** days, keep one backup every **30** days (**365:30**).
>
> Before the first interval (i.e. by default within the first 24h) it is implied > that all backup sets are kept. Additionally, if the backup destination > directory is full, the oldest backups are deleted until enough space is > available.*

This would be a great feature to have, but may be beyond the scope of the intent of this project.

**Comment by cytopia** [comment]
> I would say one tool for one task to keep things simple as possible.
> For automated deletion I would recommend `tmpreaper` or `tmpwatch` (depends on the distro)

WDYT?
