### ISSUE TITLE
no hard links to old backups under busybox

### ISSUE THREAD

**Issue by hughc** [cytopia/linux-timemachine#27]
Hi,
set the script on my Synology NAS (DS215j) to shadow a backup folder to an external drive.

Source folder was a bit under 400GB, external had 2.8 of formatted capacity. Both disks are EXT4. After only 6-7 backups, the target disk is full. Going through and manually pruning backups  via `rmdir -rf date_time_directory/**/*` freed up space in ~400GB chunks, which suggests every folder is a full backup, without linking to previously backed up files.
 
Looking at the directory structure, on disk, on the target, suggests it's OK.

```
admin_user@home-server:/volumeUSB1/usbshare/backups$ ls -la
total 40
drwxr-xr-x 9 admin_user users 4096 Jun  5 11:27 .
drwxrwxrwx 5 root       root  4096 Jun  2 18:19 ..
drwxr-xr-x 7 admin_user users 4096 May 21 20:44 2019-05-21__20-44-14
drwxr-xr-x 7 admin_user users 4096 Jun  5 11:25 2019-05-23__00-00-02
drwxr-xr-x 7 admin_user users 4096 May 25 00:00 2019-05-25__00-00-03
drwxr-xr-x 7 admin_user users 4096 May 27 00:00 2019-05-27__00-00-03
drwxr-xr-x 7 admin_user users 4096 May 28 00:00 2019-05-28__00-00-03
drwxr-xr-x 7 admin_user users 4096 May 29 00:00 2019-05-29__00-00-03
drwxr-xr-x 7 admin_user users 4096 May 31 00:00 2019-05-31__00-00-03
lrwxrwxrwx 1 admin_user users   20 Jun  2 23:03 current -> 2019-05-31__00-00-03
```
(this is missing several manually deleted backups)

Reading the source, the script should use the `--link-dest` option when the `current` dir exists, which it does. 

rsync version information:
```
admin_user@home-server:/volume1/backups$ rsync --help
rsync  version 3.0.9  protocol version 30
<many lines of options>
```

Command executed (as a scheduled task via the Synology management UI:
`bash /volume1/backups/timemachine.sh  /volume1/backups/ /volumeUSB1/usbshare/backups/ `

**Comment by cytopia** [comment]
Fixed in https://github.com/cytopia/linux-timemachine/pull/34
