### ISSUE TITLE
Backup over SSH keeps asking for password

### ISSUE THREAD

**Issue by Drugantibus** [cytopia/linux-timemachine#55]
Trying to run a backup to a remote host (`sudo ./timemachine / user@host:/path/`) results in the script asking continuously for the password, even if it is indeed correct.

**Comment by cytopia** [comment]
The script does various checks/tasks on the remote server before and after the actual backup (e.g.: https://github.com/cytopia/linux-timemachine/blob/master/timemachine#L117).

I'd recommend to use ssh keys instead, not only for the purpose of this issue.

**Comment by Drugantibus** [comment]
I managed to convince my manager to allow me to configure SSH keys, thanks!
I'd like to also make a feature suggestion: would it be possible to have the script write an error log in case something goes wrong? I know I can `timemachine ... > log.txt`, but I think it'd be more convenient for this to happen automatically, with hostnames and timestamps in the filenames :)
Let me know If you'd like me to open a separate issue for this.

**Comment by Drugantibus** [comment]
I also think it would be really useful if there was a switch like `--root-backup` (or automatic detection of backing up the / folder) so that it skips some dirs like /proc, /dev, etc

I'm not very experienced in bash development, but I can have a try at a PR if you'd like!

**Comment by cytopia** [comment]
> I managed to convince my manager to allow me to configure SSH keys, thanks!

That's good to hear!

> I'd like to also make a feature suggestion: would it be possible to have the script write an error log in case something goes wrong? I know I can `timemachine ... > log.txt`

Either way you'd probably had to write something lile `> /path/to/log/file` or if it was an argument: `-w /path/to/log/file` So I guess it does not make much of a difference, or? Additionally to note: You can currently have information log messages and error log messages separate via output direction:
`> /path/to/info/log 2> /path/to/error/log`. In general I would rather not add a code for this because of:
1. It already works with normal unix tools
2. I want to keep the code as small as possible to keep the risk of bugs low and make it easier for people to review


> I also think it would be really useful if there was a switch like `--root-backup`

Can you explain what is meant by this

**Comment by Drugantibus** [comment]
All of the listed directories are populated at boot time, so there's no need to back them up; plus, some of them don't play nice with rsync: /dev/ is full of "non-regular files" that rsync skips, and backing up /proc/ results is lots of wasted space and rsync errors since new "files" are continuously created and deleted ("file has vanished"), and there's no data there anyway.

This can already be achieved by appending options to rsync, but I imagine backing up `/` is a pretty common use case.

**Comment by cytopia** [comment]
With what rsync option do you usually do a `/` backup?

**Comment by cytopia** [comment]
@Drugantibus I will mark this question regarding SSH password as solved. If you have a follow up question for the default arguments, please use a new issue and provide your suggestions.
