### ISSUE TITLE
Is there a reason for not allowing a remote source?

### ISSUE THREAD

**Issue by dmi-000** [cytopia/linux-timemachine#56]
What would break if I changed 
  ! -d "${1}" ;
to
  ! dir_exists "${1}"
?

**Comment by cytopia** [comment]
Remote to local backups where never a use case (yet), so I ensured it works the other way round and verifies any unsupported usage.

**Comment by dmi-000** [comment]
Thank you. In that case, I will experiment with extending it for my use cases without depending on it being supported.

**Comment by cytopia** [comment]
@dmi-000 remote source is now coming: https://github.com/cytopia/linux-timemachine/pull/61
