### ISSUE TITLE
exclude file/dir options?

### ISSUE THREAD

**Issue by gebyt-rybrit** [cytopia/linux-timemachine#57]
Thank you for timemachine!  is there an option to 'exclude' directories/files like there is with rsync using syntax "--exclude" ?

**Comment by cytopia** [comment]
Yes, you can simply append `rsync` arguments after last two `--` as such:

```
timemachine src/ dst/ -- --no-times --exclude ...
```

**Comment by gebyt-rybrit** [comment]
great, thank you!

**Comment by cytopia** [comment]
@gebyt-rybrit closing as your question seems to be answered :)
