### ISSUE TITLE
suggestion to add --without-overlaps option

### ISSUE THREAD

**Issue by timoshka-lab** [cytopia/linux-timemachine#58]
I like this script and it very useful for me to backup my NAS storage. Thank you!

Here i would like to suggest the option which will helps to do backup process without overlaps.
In my situation, i have to backup my ssd storage per 10 minutes, and keep the backups in daily cycle.
So sometimes, the backup process getting overlapped, and rsync calculating diffs from "not really current" backup directory.

I made some changes for your script, so i would like you to check my pull request bellow.

**Comment by cytopia** [comment]
@timoshka-lab I would rather go by the [kiss principle](https://en.wikipedia.org/wiki/KISS_principle) and keep the purpose of this tool soley the backup functionality. Wit more features there will be potential errors in the code.

But nonetheless, you can use [flock](https://linux.die.net/man/2/flock) also a standalone tool for this very purpose to achieve the same.
