### ISSUE TITLE
Suggestion | Allow remote source

### ISSUE THREAD

**Issue by dwaynehulsman** [cytopia/linux-timemachine#60]
Currently, I'm trying to make my backup server retrieve the files from the actual source (remote server) and put it on a local destination directory. It seems that you're unable to use a remote source, this would be very handy.

**Comment by cytopia** [comment]
@dwaynehulsman Thanks for the suggestion. I will look into this.

**Comment by cytopia** [comment]
@dwaynehulsman implemented in `v1.1` via: https://github.com/cytopia/linux-timemachine/pull/61
