### ISSUE TITLE
Problem with some paths/volume names

### ISSUE THREAD

**Issue by silverdr** [cytopia/linux-timemachine#69]
When trying to do backup to a mounted "pendrive":
```
silverdr:~$ timemachine /home/silverdr /media/silverdr/Angela\'s\ Files/
/usr/local/bin/timemachine: 1: eval: Syntax error: Unterminated quoted string
```
I believe this is caused by the volume label including apostrophe character.

**Comment by cytopia** [comment]
@silverdr thanks for reporting this. I will have a look at it.

**Comment by cytopia** [comment]
@silverdr you want to give the `release-1.3.1` branch a try and check if this solves your issues.

PR is here: https://github.com/cytopia/linux-timemachine/pull/70

**Comment by silverdr** [comment]
Thank you very much for the prompt reaction! I'll have a look at the branch you mentioned and report back.

**Comment by silverdr** [comment]
I can confirm that running the `release-1.3.1` branch version produces correct backups without errors.

**Comment by cytopia** [comment]
It is still WIP though, as I had to switch from POSIX shell to bash and also some of the CI tests need fixing for special chars. Will close this issue as soon as I've merged the PR.

The currently working commit is: https://github.com/cytopia/linux-timemachine/commit/5630ce335700b3ee11615b06784900be1f22b84b

**Comment by cytopia** [comment]
@silverdr new version has been merged and tagged: `v1.3.1`

**Comment by silverdr** [comment]
> I had to switch from POSIX shell to bash
Is the full release non-bash-shell compatible?

**Comment by cytopia** [comment]
> > I had to switch from POSIX shell to bash
> > Is the full release non-bash-shell compatible?

Yes, I switched back to `/bin/sh` after I fixed the issue: https://github.com/cytopia/linux-timemachine/blob/master/timemachine#L1
