### ISSUE TITLE
How to skip broken soft links?

### ISSUE THREAD

**Issue by lijxug** [cytopia/linux-timemachine#73]
When broken soft links exist, timemachine thinks it failed its job and doesn't proceed the final step.

**Comment by cytopia** [comment]
@lijxug can you provide some steps to reproduce. This behaviour does work for me:

Directories before:
```shell
$ tree
.
├── dst
└── src
    ├── file
    ├── working -> file
    └── wrong -> nonexisting

2 directories, 3 files
```
Running timemachine
```shell
$ timemachine src/ dst/
```
Directories after
```shell
$ tree
.
├── dst
│   ├── 2022-03-31__04-46-51
│   │   ├── file
│   │   ├── working -> file
│   │   └── wrong -> nonexisting
│   └── current -> 2022-03-31__04-46-51
└── src
    ├── file
    ├── working -> file
    └── wrong -> nonexisting

4 directories, 6 files
```

**Comment by cytopia** [comment]
@lijxug  I've marked this as invalid as I was not able to reproduce this behavior and there was no response for a long time. Feel free to enhance this issue.
