### ISSUE TITLE
Missing destination folder is resulting in script fail

### ISSUE THREAD

**Issue by h0ysala** [cytopia/linux-timemachine#74]
When target folder does not exist on disk, script fails due to missing variable 

https://github.com/cytopia/linux-timemachine/blob/c4629a31cf71a8b3b4c6bc0514af98e2e168081d/timemachine#L184

**Comment by cytopia** [comment]
Can you add some details on when this fails? Currently not able to reproduce, If I just omit the target dir

**Comment by cytopia** [comment]
@h0ysala I've marked this as invalid as I was not able to reproduce this behavior and there was no response for ~6 weeks. Feel free to enhance this issue.
