### ISSUE TITLE
Problem with moving .inprogress dir

### ISSUE THREAD

**Issue by sdreisei** [cytopia/linux-timemachine#79]
Hi,
I'm just starting out using linux-timemachine. I wanted to save my entire home directory to an open veracrypt container on a mounted USB drive. Executing 
`
timemachine -d /home/test /media/veracrypt1/test -- --dry-run --verbose
`
gives me the error message (after running through all the files in the directory)
`
2022-09-08 13:06:35 timemachine: [DEBUG] Renaming local dir: '/media/veracrypt1/test/.inprogress' -> '/media/veracrypt1/test/2022-09-08__13-06-27'
`
`
2022-09-08 13:06:35 timemachine: [DEBUG] $ mv '/media/veracrypt1/test/.inprogress' '/media/veracrypt1/test/2022-09-08__13-06-27'
`
`
mv: cannot stat '/media/veracrypt1/test/.inprogress': No such file or directory
`
`
2022-09-08 13:06:35 timemachine: [ERROR] Failed to rename local dir
`
I manually created a `/media/veracrypt1/test/.inprogress` file, so it can't be a permissions thing. The veracrypt container is also still open through all this. I feel like I'm missing something obvious; could someone please point me in the right direction?

**Comment by cytopia** [comment]
I guess the issue is `--dry-run` which did not create a `.inprogress` directory, as it was simply a dry-run

**Comment by sdreisei** [comment]
Gee, now I feel stupid :). I thought that that was the first thing I had tried, but apparently not. Thanks, that was it. Maybe you could add a comment to the relevant part of the FAQ, where the `--dry-run` option is mentioned.
