### ISSUE TITLE
remote backups do not work

### ISSUE THREAD

**Issue by ghost** [cytopia/linux-timemachine#9]
Doing something like:

 timemachine localdir server:/tmp/remotedir

fails.

1) There is code to check the destination folder exists (-d "${2}") which only works on local machine
2) Even without this test the tidy up code after the rsync 2/3 and 3/3 will fail since these also only work n local machine.

**Comment by jeksmith** [comment]
One workaround is to backup to a local directory. And then separately use rsync to copy the backup dir to a remote machine.

rsync -az -H --delete $SOURCE $DESTINATION

**Comment by cytopia** [comment]
@ghost @jeksmith this is now implemented
